### DISCUSSION TITLE
Trouble getting started

### DISCUSSION THREAD

**Discussion by thangduong** [nest-desktop/nest-desktop#438] [General] [answered]
Apologize if this is not the right forum. If not, is there a better one for these newbie questions? 

I just followed the directions for installation via docker compose  here: https://nest-desktop.readthedocs.io/en/latest/user/setup.html#via-docker-compose-linux-windows-apple.

Once everything is up and running, I build a small network and hit simulate and get "Failed to find NEST Simulator."  I tried starting nest server manually with "nest-server start", and it solves this issue, but now I get "attribute-less object (assign or del)".  Not really sure what that means.  It's just a very simple network.  I maybe something I did wrong. 

![image](https://user-images.githubusercontent.com/2172515/201789565-10cad880-24d6-4dcf-9d6b-027ba1780bb9.png)

**Comment by babsey** [comment]
We apologize for the inconvenience.

For the first issue: 
- Can you show the config file for docker-compose?

For the second issue:
The error "attribute-less object (assign or del)" appears because of RestrictedPython execution.
The RestrictedPython slighly protects the host from possible attack from outside (See https://nest-simulator.readthedocs.io/en/latest/connect_nest/nest_server.html#security-considerations).

Did you try to set an environment variable before you start NEST Server?
```
export NEST_SERVER_RESTRICTION_OFF=true
nest-server start
```

**Reply by thangduong** [reply]
Here is the docker-compose.yml:
```
version: '3'

services:
  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-desktop:3.1
    ports:
      - '8000:8000'

  nest-simulator:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.2
    environment:
      NEST_CONTAINER_MODE: 'nest-server'
      NEST_SERVER_BUFFER_SIZE: 65535
      NEST_SERVER_HOST: '0.0.0.0'
      NEST_SERVER_MODULES: 'nest,numpy'
      NEST_SERVER_PORT: 5000
      NEST_SERVER_RESTRICTION_OFF: 1
    ports:
      - '5000:5000'
```

Adding 
```
export NEST_SERVER_RESTRICTION_OFF=true
```
Works.  I can run now, but still need to manually run nest-server.
