### DISCUSSION TITLE
YAML format for models and projects

### DISCUSSION THREAD

**Discussion by babsey** [nest-desktop/nest-desktop#512] [Ideas]
I am playing with some idea whether NEST Desktop provides YAML format for projects and models.
It could be more consistent with NESTML which also uses YAML format.

An example of YAML format of a project:
```
---
network:
  connections:
  - source: 1
    target: 0
  nodes:
  - model: iaf_psc_alpha
    params:
    - id: C_m
      value: 250
      visible: false
    - id: E_L
      value: -70
      visible: false
    - id: I_e
      value: 0
      visible: false
    - id: V_m
      value: -70
      visible: false
    - id: V_reset
      value: -70
      visible: false
    - id: V_th
      value: -55
      visible: false
    - id: t_ref
      value: 2
      visible: false
    - id: tau_m
      value: 10
      visible: false
    - id: tau_syn_ex
      value: 2
      visible: false
    - id: tau_syn_in
      value: 2
      visible: false
    size: 100
  - model: voltmeter
    size: 1
simulation:
  kernel:
    localNumThreads: 1
    resolution: 0.1
    rngSeed: 1
  time: 1000
```
compared to:
```
{
	"network": {
		"connections": [
			{
				"source": 1,
				"target": 0
			}
		],
		"nodes": [
			{
				"model": "iaf_psc_alpha",
				"params": [
					{
						"id": "C_m",
						"value": 250,
						"visible": false
					},
					{
						"id": "E_L",
						"value": -70,
						"visible": false
					},
					{
						"id": "I_e",
						"value": 0,
						"visible": false
					},
					{
						"id": "V_m",
						"value": -70,
						"visible": false
					},
					{
						"id": "V_reset",
						"value": -70,
						"visible": false
					},
					{
						"id": "V_th",
						"value": -55,
						"visible": false
					},
					{
						"id": "t_ref",
						"value": 2,
						"visible": false
					},
					{
						"id": "tau_m",
						"value": 10,
						"visible": false
					},
					{
						"id": "tau_syn_ex",
						"value": 2,
						"visible": false
					},
					{
						"id": "tau_syn_in",
						"value": 2,
						"visible": false
					}
				],
				"size": 100
			},
			{
				"model": "voltmeter",
				"size": 1
			}
		]
	},
	"simulation": {
		"kernel": {
			"localNumThreads": 1,
			"resolution": 0.1,
			"rngSeed": 1
		},
		"time": 1000
	}
}
```
