### ISSUE TITLE
macOS uses port 5000, conflicts with NEST Simulator

### ISSUE THREAD

**Issue by apdavison** [nest-desktop/nest-desktop#381]
**Describe the bug**
By default the Docker container runs the NEST Simulator on port 5000.

On macOS Monterey, however, this port is already in use by the operating system. There is a [workaround](https://apple.stackexchange.com/questions/431154/controlcenter-app-listens-to-port-5000-tcp-on-monterey-os-is-that-normal-why-d) but I wonder if you would consider switching to a different port? 

**To Reproduce**
Steps to reproduce the behavior. On a Mac running Mac OS Montery run 
1. `wget https://raw.githubusercontent.com/nest-desktop/nest-desktop/main/docker-compose.yml`
2. `docker-compose up --build`
3. see error message "ERROR: for nest-simulator  Cannot start service nest-simulator: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use"

**Expected behavior**
The two Docker containers should start, using ports that are not in use by the OS.

**Desktop (please complete the following information):**
 - macOS Monterey version 12.3.1

**Comment by babsey** [comment]
Thank you for reporting this issue. 

We are aware of the port conflicting of NEST Server in macOS.
The current state is that we are looking for other default port for NEST Server  (https://github.com/nest/nest-simulator/issues/2321).
I hope that we will come to the solution at NEST Conference 2022 this week.

For now you can use this docker-compose config to set another NEST Server port, e.g. 15000:

docker-compose.yml
```
version: "3"

services:
  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-desktop:3.1
    environment:
      NEST_SIMULATOR_PORT: 15000
    ports:
      - 8000:8000

  nest-simulator:
    image: docker-registry.ebrains.eu/nest/nest-simulator:3.3
    environment:
      NEST_CONTAINER_MODE: nest-server
      NEST_SERVER_HOST: 0.0.0.0
      NEST_SERVER_MODULES: nest,numpy
      NEST_SERVER_PORT: 15000
      NEST_SERVER_RESTRICTION_OFF: 1
    ports:
      - 15000:15000
```

We will add user doc about this configuration.
